"""Data models shared across scanner components."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from razin.types import Confidence, Severity

type FrontmatterData = dict[str, Any] | None


@dataclass(frozen=True)
class Evidence:
    """Evidence location and snippet for a finding."""

    path: str
    line: int | None
    snippet: str


@dataclass(frozen=True)
class FindingCandidate:
    """Pre-normalized finding generated by a detector."""

    rule_id: str
    score: int
    confidence: Confidence
    title: str
    description: str
    evidence: Evidence
    recommendation: str
    internal_rule_id: str | None = None


@dataclass(frozen=True)
class Finding:
    """Serialized finding representation used in reports."""

    id: str
    severity: Severity
    score: int
    confidence: Confidence
    title: str
    description: str
    evidence: Evidence
    skill: str
    rule_id: str
    recommendation: str

    def to_dict(self) -> dict[str, Any]:
        """Convert finding to a JSON-serializable dictionary."""
        return asdict(self)


@dataclass(frozen=True)
class Summary:
    """Per-skill summary report."""

    skill: str
    overall_score: int
    overall_severity: Severity
    finding_count: int
    counts_by_severity: dict[Severity, int]
    top_risks: list[dict[str, object]]

    def to_dict(self) -> dict[str, Any]:
        """Convert summary to a JSON-serializable dictionary."""
        return asdict(self)


@dataclass(frozen=True)
class DocumentField:
    """Document field and location metadata."""

    path: tuple[str, ...]
    value: str
    line: int
    snippet: str


@dataclass(frozen=True)
class DocumentKey:
    """Document key and location metadata."""

    path: tuple[str, ...]
    key: str
    line: int
    snippet: str


@dataclass(frozen=True)
class ParsedSkillDocument:
    """Parsed SKILL.md document with extracted fields and keys."""

    file_path: Path
    raw_text: str
    frontmatter: FrontmatterData
    body: str
    fields: list[DocumentField]
    keys: list[DocumentKey]


@dataclass(frozen=True)
class ScanResult:
    """Aggregated scan execution result."""

    scanned_files: int
    total_findings: int
    aggregate_score: int
    aggregate_severity: Severity
    counts_by_severity: dict[Severity, int]
    findings: list[Finding]
    duration_seconds: float
    warnings: list[str]
    cache_hits: int
    cache_misses: int
