"""Centralized constants for Razin."""

from __future__ import annotations

from .cache import (
    CACHE_FILENAME,
    CACHE_TEMP_PREFIX,
    CACHE_TEMP_SUFFIX,
    CACHE_VERSION,
    FILE_HASH_CHUNK_SIZE,
    LEGACY_CACHE_ENGINE,
)
from .config import (
    CONFIG_FILENAME,
    DEFAULT_DETECTORS,
    DEFAULT_MAX_FILE_MB,
    DEFAULT_SKILL_GLOBS,
)
from .engines import CLI_ENGINE_CHOICES, ENGINE_DSL, REMOVED_ENGINE_CHOICES
from .ids import FINDING_ID_HEX_LENGTH
from .reporting import FINDINGS_FILENAME, REPORT_TEMP_PREFIX, REPORT_TEMP_SUFFIX, SUMMARY_FILENAME

__all__ = [
    "CACHE_FILENAME",
    "CACHE_TEMP_PREFIX",
    "CACHE_TEMP_SUFFIX",
    "CACHE_VERSION",
    "CONFIG_FILENAME",
    "DEFAULT_DETECTORS",
    "DEFAULT_MAX_FILE_MB",
    "DEFAULT_SKILL_GLOBS",
    "CLI_ENGINE_CHOICES",
    "ENGINE_DSL",
    "REMOVED_ENGINE_CHOICES",
    "FINDING_ID_HEX_LENGTH",
    "FILE_HASH_CHUNK_SIZE",
    "LEGACY_CACHE_ENGINE",
    "FINDINGS_FILENAME",
    "REPORT_TEMP_PREFIX",
    "REPORT_TEMP_SUFFIX",
    "SUMMARY_FILENAME",
]
