"""Constants for the ``razin init`` command."""

from __future__ import annotations

from razin.constants.profiles import DEFAULT_PROFILE, ProfileName

INIT_CONFIG_TEMP_PREFIX: str = ".tmp-init-"
INIT_CONFIG_TEMP_SUFFIX: str = ".yaml"

INIT_PROFILE_CHOICES: tuple[str, ...] = ("strict", "balanced", "audit")
INIT_DEFAULT_PROFILE: ProfileName = DEFAULT_PROFILE

INIT_GENERATED_HEADER: str = "# Generated by razin init"
INIT_ADVANCED_SECTION_COMMENTS: tuple[str, ...] = (
    "# Optional advanced sections",
    "# tool_prefixes:",
    "#   - MCP_",
    "# detectors:",
    "#   enabled: []",
    "#   disabled: []",
    "# typosquat:",
    "#   baseline: []",
)
